{% set name = "flake8-functions" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_functions-{{ version }}.tar.gz
  sha256: 5446626673a9faecbf389fb411b90bdc87b002c387b72dc097b208e7a58f2a1c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - mr-proper
    - pytest
    - python >=3.6
    - setuptools

test:
  imports:
    - flake8_functions
  commands:
    - pip check
    - flake8 --version | grep flake8-functions
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/best-doctor/flake8-functions
  summary: A flake8 extension that checks functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
